-- Historical reference for the original member-feature rollout.
-- Do not apply this file to a current environment.
-- The executable schema source is src/main/resources/db/migration and Hibernate now validates it.

BEGIN;

CREATE TABLE IF NOT EXISTS app_user (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(254) NOT NULL,
    password_hash varchar(100) NOT NULL,
    nickname varchar(20) NOT NULL,
    role varchar(20) NOT NULL,
    status varchar(20) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    last_login_at timestamp,
    CONSTRAINT uk_app_user_email UNIQUE (email),
    CONSTRAINT ck_app_user_role CHECK (role IN ('USER', 'ADMIN')),
    CONSTRAINT ck_app_user_status CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE IF NOT EXISTS refresh_token (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    token_hash varchar(64) NOT NULL,
    expires_at timestamp NOT NULL,
    revoked_at timestamp,
    created_at timestamp NOT NULL,
    replaced_by_token_id bigint
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_refresh_token_hash ON refresh_token(token_hash);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user ON refresh_token(user_id);

ALTER TABLE popup_like ADD COLUMN IF NOT EXISTS user_id bigint;
ALTER TABLE popup_like ALTER COLUMN anonymous_visitor_id DROP NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS uk_popup_like_user
    ON popup_like(popup_store_id, user_id) WHERE user_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_popup_like_user ON popup_like(user_id);

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_popup_like_user') THEN
        ALTER TABLE popup_like
            ADD CONSTRAINT fk_popup_like_user FOREIGN KEY (user_id) REFERENCES app_user(id);
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_popup_like_owner') THEN
        ALTER TABLE popup_like ADD CONSTRAINT ck_popup_like_owner CHECK (
            (anonymous_visitor_id IS NOT NULL AND user_id IS NULL)
            OR (anonymous_visitor_id IS NULL AND user_id IS NOT NULL)
        );
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS popup_favorite (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    popup_store_id bigint NOT NULL REFERENCES popup_store(id),
    created_at timestamp NOT NULL,
    CONSTRAINT uk_popup_favorite_user_store UNIQUE (user_id, popup_store_id)
);
CREATE INDEX IF NOT EXISTS idx_popup_favorite_user_created
    ON popup_favorite(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_popup_favorite_store ON popup_favorite(popup_store_id);

CREATE TABLE IF NOT EXISTS visit_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    popup_store_id bigint NOT NULL REFERENCES popup_store(id),
    visited_at timestamp NOT NULL,
    visit_date date NOT NULL,
    source varchar(30) NOT NULL,
    route_session_id varchar(64),
    created_at timestamp NOT NULL,
    CONSTRAINT uk_visit_user_store_date UNIQUE (user_id, popup_store_id, visit_date),
    CONSTRAINT ck_visit_source CHECK (source IN ('NAVIGATION_ARRIVAL', 'MANUAL_CONFIRMATION'))
);
CREATE INDEX IF NOT EXISTS idx_visit_user_visited ON visit_history(user_id, visited_at DESC);
CREATE INDEX IF NOT EXISTS idx_visit_store ON visit_history(popup_store_id);

CREATE TABLE IF NOT EXISTS popup_review (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES app_user(id),
    popup_store_id bigint NOT NULL REFERENCES popup_store(id),
    visit_history_id bigint NOT NULL REFERENCES visit_history(id),
    rating integer NOT NULL,
    content varchar(1000) NOT NULL,
    created_at timestamp NOT NULL,
    updated_at timestamp NOT NULL,
    CONSTRAINT uk_review_user_store UNIQUE (user_id, popup_store_id),
    CONSTRAINT ck_review_rating CHECK (rating BETWEEN 1 AND 5),
    CONSTRAINT ck_review_content_length CHECK (char_length(content) BETWEEN 10 AND 1000)
);
CREATE INDEX IF NOT EXISTS idx_review_store_created ON popup_review(popup_store_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_review_user ON popup_review(user_id);
CREATE INDEX IF NOT EXISTS idx_review_visit ON popup_review(visit_history_id);

CREATE TABLE IF NOT EXISTS popup_review_summary (
    popup_store_id bigint PRIMARY KEY REFERENCES popup_store(id),
    rating_sum bigint NOT NULL DEFAULT 0,
    review_count bigint NOT NULL DEFAULT 0,
    average_rating double precision NOT NULL DEFAULT 0,
    updated_at timestamp NOT NULL,
    CONSTRAINT ck_review_summary_nonnegative CHECK (rating_sum >= 0 AND review_count >= 0),
    CONSTRAINT ck_review_summary_average CHECK (average_rating BETWEEN 0 AND 5)
);

COMMIT;
